### ISSUE TITLE
Content Exists Risk

### ISSUE THREAD

**Issue by liugezhou** [deepseek-ai/awesome-deepseek-integration#13]
In the input content, the interface will report the above error. 
What is the reason? 
Do I need to do anything with the input content?

**Comment by zzk2021** [comment]
same issue? but I run successfully on other mechine, it's strange.

**Comment by soloice** [comment]
Typically, we refuse to answer harmful queries (e.g.: violence/discrimination content). Occasionally, normal inputs are misclassified, so you get a "Content Exists Risk" error. If you feel you are experiencing such an issue, you can contact us in WeChat group or send a email to report your use case.

We are continuously refining our safety strategies to minimize the probility of misclassification and improve user experience.

**Comment by soloice** [comment]
> same issue? but I run successfully on other mechine, it's strange.

Probably because we've updated our safety strategy before you call our API on another machine.
