### ISSUE TITLE
chat box 422错误

### ISSUE THREAD

**Issue by amiliyaai** [deepseek-ai/awesome-deepseek-integration#14]
![image](https://github.com/deepseek-ai/awesome-deepseek-integration/assets/68532193/f9f30df1-20d3-463d-a7e1-d093b28bf9d4)

**Comment by amiliyaai** [comment]
![image](https://github.com/deepseek-ai/awesome-deepseek-integration/assets/68532193/a96c9fb2-c1c3-4d7c-82cd-d12cd4137c5b)

**Comment by Everfighting** [comment]
同样的错误，感觉是chatbox更新造成的，之前的版本没有这个错误。但是自己手残升级了一下客户端

**Comment by Everfighting** [comment]
我看官方文档错误是422参数错误，不知道是不是base_url需要修改成对应的版本，麻烦看到回复一下。

**Comment by amiliyaai** [comment]
> 我看官方文档错误是422参数错误，不知道是不是base_url需要修改成对应的版本，麻烦看到回复一下。

你好，
  我的ChatBox版本是1.3.8，我个人试了两个url，如下：
  https://api.deepseek.com，422错误
  https://api.deepseek.com/v1，404错误
  实在不知道是我个人问题还是版本更新的问题，因为今天才下的ChatBox。

**Comment by Everfighting** [comment]
https://github.com/Bin-Huang/chatbox/issues/1347 @amiliyaai  看这个，是chatbox软件更新的原因，官方已经重新给了一个版本，你下载新的试试，应该不是deepseek的问题

**Comment by amiliyaai** [comment]
> [Bin-Huang/chatbox#1347](https://github.com/Bin-Huang/chatbox/issues/1347) @amiliyaai 看这个，是chatbox软件更新的原因，官方已经重新给了一个版本，你下载新的试试，应该不是deepseek的问题

感谢，这个版本正常使用。

**Comment by Everfighting** [comment]
这个issue可以关了 @amiliyaai
