### ISSUE TITLE
siri 指令如何添加？

### ISSUE THREAD

**Issue by lmmsoft** [deepseek-ai/awesome-deepseek-integration#2]
文档不全呀

**Comment by DillionApple** [comment]
点击文档大标题（深度求索 (shortcut)）会跳转到快捷指令页面，在里面就可以添加了。

**Comment by lmmsoft** [comment]
Thanks, 太隐蔽了！

**Comment by Suffton** [comment]
没看明白呢？哪个文档，哪个标题？

**Comment by EnderLiuwj** [comment]
> 没看明白呢？哪个文档，哪个标题？

下面这个链接，点击大标题[深度求索 (shortcut)](https://www.icloud.com/shortcuts/b75899492ead45ef9a47cfce89334bf0)的超链接

https://github.com/deepseek-ai/awesome-deepseek-integration/tree/main/docs/siri_deepseek_shortcut
