### ISSUE TITLE
Chatbox(v1.3.14) 连接DeepSeek出现422 

### ISSUE THREAD

**Issue by Cyan2077** [deepseek-ai/awesome-deepseek-integration#23]
刚下载的Chatbox(v1.3.14)，连接DeepSeek 出现422错误。之前看到有人也出现过类似错误，但是这个最新版本好像又出现了

API Error: Status Code 422, Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: sequence, expected a string at line 1 column 40

![image](https://github.com/deepseek-ai/awesome-deepseek-integration/assets/151855984/e82241f6-6de0-48ea-8927-a9aa1351d0c2)

**Comment by LYYJCY** [comment]
应该怎么解决？

**Comment by EnochxynL** [comment]
目前发现deepseek在chatbox要纯文本对话，而且必须ai一句user一句交替进行，如果这个规则破坏了就重新开个新对话来聊天了。希望以后能更加兼容多媒体格式
