### ISSUE TITLE
continue 的 temperature 配置是否应该 1.0 ?

### ISSUE THREAD

**Issue by HustCoderHu** [deepseek-ai/awesome-deepseek-integration#30]
refer to <https://platform.deepseek.com/api-docs/temperature/>

**Comment by SuperNG6** [comment]
同好奇，官方文档对于 deepseek-coder，建议使用默认 temperature 值（1.0）。对于 deepseek-chat 则是 0
![5PTUbK](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2024-08-20/5PTUbK.png)
