### ISSUE TITLE
deepseek 在cursor中无法联网

### ISSUE THREAD

**Issue by lesong36** [deepseek-ai/awesome-deepseek-integration#35]
deepseek-chat model is working but not with @web.

![image](https://github.com/user-attachments/assets/faca1064-5724-4bad-81a6-fa6aad81f70a)

![image](https://github.com/user-attachments/assets/964c5317-9269-495f-80de-0cb081d154bd)
![image](https://github.com/user-attachments/assets/c06bb4ab-baf2-4376-8a95-e56945643649)

**Comment by soloice** [comment]
是的 deepseek 暂时不支持联网
