### ISSUE TITLE
Is there any way limit token response?

### ISSUE THREAD

**Issue by MrTimonM** [deepseek-ai/awesome-deepseek-integration#4]
Hi, I am wondering if there's a way to get response in a limited token like 200?
Thank you.

**Comment by DillionApple** [comment]
Just set the max_tokens parameter to 200, this tells the api to output less than 200 tokens. e.g.: 

chat_completion = client.chat.completions.create(
    model="deepseek-chat",
    messages=[{ "role": "user", "content": f"hi"}],
    max_tokens=200
)
