### ISSUE TITLE
为什么调用会显示模型不存在

### ISSUE THREAD

**Issue by blackxiaobai** [deepseek-ai/awesome-deepseek-integration#6]

**Comment by blackxiaobai** [comment]
{
  "detail": "Model Not Exist"
}

**Comment by Bjorne1** [comment]
沉浸式翻译插件就调通了一次。后面再用就模型不存在了。Glarity 直接 bad request

**Comment by TCOTC** [comment]
指定对模型名称了吗？

![image](https://github.com/deepseek-ai/awesome-deepseek-integration/assets/78434827/06d5bd58-010d-4656-b5d4-26593400fe3d)

**Comment by DillionApple** [comment]
不用加星号，星号是提示有备注的意思。
